# Linear Algebra - by Numpy

## 向量

In [1]:
import numpy as np # include, using 

In [5]:
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [7]:
ls = [1,2,3,4]
type(ls)

list

In [8]:
type(v)

numpy.ndarray

### 特殊向量

In [20]:
np.linspace(0, 9, 10) # 等差数列

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## 矩阵

In [21]:
M = np.array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [23]:
ls = [[1,2],[3,4]]
type(ls)

list

In [24]:
M.size

4

In [25]:
M.shape # dimension 2 x 2

(2, 2)

In [27]:
M.shape[1]

2

## 特殊矩阵

In [31]:
np.random.rand(4,5) 

array([[0.98230983, 0.60662292, 0.43571422, 0.82429881, 0.15872953],
       [0.31055275, 0.87298291, 0.08552793, 0.73275129, 0.83795975],
       [0.48185722, 0.23059928, 0.29524315, 0.63854732, 0.01663189],
       [0.84363427, 0.495116  , 0.00186978, 0.50230105, 0.41213289]])

In [32]:
np.random.randn(4,5)

array([[ 1.44865407,  1.61432882,  0.80083504, -0.91568849, -0.69933454],
       [-2.46848164,  0.83716433, -1.12205084, -2.13346927, -0.43721545],
       [ 0.48057103,  0.76245106,  2.41157121,  0.35469928,  1.50361537],
       [ 0.61906085,  0.01210198,  1.10615218, -0.67630285, -1.03027976]])

In [33]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [34]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# 基本运算

In [37]:
v

array([1, 2, 3, 4])

In [38]:
v + 1

array([2, 3, 4, 5])

In [39]:
v * 2

array([2, 4, 6, 8])

In [40]:
M

array([[1, 2],
       [3, 4]])

In [41]:
M - 1

array([[0, 1],
       [2, 3]])

In [42]:
M * 2

array([[2, 4],
       [6, 8]])

In [43]:
M.T

array([[1, 3],
       [2, 4]])

In [44]:
np.transpose(M)

array([[1, 3],
       [2, 4]])

### 矩阵乘法

In [45]:
M @ M

array([[ 7, 10],
       [15, 22]])

In [46]:
np.matmul(M,M)

array([[ 7, 10],
       [15, 22]])

### Element-wise Multiplication

In [47]:
M * M

array([[ 1,  4],
       [ 9, 16]])

In [48]:
np.multiply(M,M)

array([[ 1,  4],
       [ 9, 16]])

### $ AB \neq BA $ 

In [49]:
P = np.ones((2,2))
P

array([[1., 1.],
       [1., 1.]])

In [50]:
M @ P

array([[3., 3.],
       [7., 7.]])

In [51]:
P @ M

array([[4., 6.],
       [4., 6.]])

### Inverse

In [52]:
np.linalg.inv(M)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [53]:
np.linalg.inv(M) @ M

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

In [54]:
np.linalg.pinv(M) # pseudo inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# 行列式 determinant

Determinants can be used to see if a system of n linear equations in n variables has a unique solution. This is useful for homework problems and the like, when the relevant computations can be performed exactly.

However, when solving real numerical problems, the determinant is rarely used, as it is a very poor indicator of how well you can solve a system of equations, and furthermore, it is typically very expensive to compute directly. Other quantities (such as singular values) provide better indications of 'solvability', and other techniques (Gaussian elimination, QR decompositions, etc.) are better for solving systems of equations.

The determinant also gives the (signed) volume of the parallelepiped whose edges are the rows (or columns) of a matrix. I find this interpretation to be the most intuitive, and many standard results for determinants can be understood using this viewpoint. (However, I have rarely had a practical need to compute volumes using determinants.) The volume interpretation is often useful when computing multidimensional integrals ('change of variables'). It is also useful for understanding (or defining) the 'cross product' in physics or mechanics.

In [8]:
import numpy as np
from numpy.linalg import det

A = np.array([[1,1],[1,0]])
B = np.eye(3) * 2
det(A),det(B)

(-1.0, 7.999999999999998)

# 其它常用操作

## extract items that satisfy a given condition

Q: Extract all odd numbers from arr

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired output:

array([1, 3, 5, 7, 9])

In [2]:
import numpy as np
# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Solution
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

## reshape

In [6]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
arr.reshape((2,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [7]:
arr.reshape((3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
arr43 = arr.reshape((-1, 3))
arr43

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

# flatten

In [14]:
arr43.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## stacking

In [32]:
a = np.array([[1,2,3], [-1,-2,-3]])
b = np.array([[2,3,4], [-2,-3,-4]])
np.hstack((a,b))

array([[ 1,  2,  3,  2,  3,  4],
       [-1, -2, -3, -2, -3, -4]])

In [34]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [-1, -2, -3],
       [ 2,  3,  4],
       [-2, -3, -4]])