# NumPy 复习

In [1]:
import numpy as np

A=np.array([[1,2],[3,4]])

In [3]:
B=np.array([[0,-1],[-1,-2]])

In [4]:
A*B # element-wise multiplication

array([[ 0, -2],
       [-3, -8]])

In [5]:
A@B

array([[ -2,  -5],
       [ -4, -11]])

In [6]:
from math import sqrt

C=np.array([[sqrt(2)/2, -sqrt(2)/2],[sqrt(2)/2, sqrt(2)/2]])
C

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [7]:
C@np.array([[1],[1]])

array([[0.        ],
       [1.41421356]])

In [8]:
D=np.array([[3,0],[0,4]])
D

array([[3, 0],
       [0, 4]])

In [9]:
D @ np.array([[1],[1]])

array([[3],
       [4]])

In [15]:
U,S,Vh = np.linalg.svd ( C @ D ) # 奇异值分解 

In [12]:
U

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

In [13]:
S

array([4., 3.])

In [18]:
F=[[1,2],[3,6]]

In [19]:
np.linalg.matrix_rank(F)  # 秩

1

In [37]:
import numpy as np

a=np.random.randn(5)
a=a.reshape((1,5))
b=np.random.randn(5,1)
assert(b.shape == (5,1) and a.shape ==(1,5))

# "np.dot(a,b)" performs a matrix multiplication on a and b, whereas "a*b" performs an element-wise multiplication
print(np.dot(a,b))
print(np.dot(b,a))

[[0.22708572]]
[[-0.21722663  0.70995357  0.28636931 -0.05298248 -0.15846203]
 [-0.27252294  0.8906764   0.3592663  -0.06646949 -0.19879946]
 [ 0.25240027 -0.82491025 -0.33273864  0.06156148  0.18412042]
 [-0.74868707  2.44690558  0.98699226 -0.18260791 -0.54615068]
 [ 0.09456422 -0.30906064 -0.12466376  0.02306461  0.06898251]]


In [38]:
def sigmoid(x):
    """
    Compute sigmoid of x.

    Arguments:
    x -- A matrix

    Return:
    s -- sigmoid(x)
    """
    
    s = 1/(1+np.exp(np.negative(x)))
    
    return s

def sigmoid_grad(x):
    return sigmoid(x)*(1-sigmoid(x))

In [39]:
sigmoid([[-1,-2],[1,2]])
sigmoid_grad([[-1,-2],[1,2]])

array([[0.19661193, 0.10499359],
       [0.19661193, 0.10499359]])

### Statistics

In [40]:
mean(A[:,3])

23.0

In [41]:
std(A[:,3]), var(A[:,3])

(14.142135623730951, 200.0)

In [42]:
A[:,3].min(), A[:,3].max()

(3, 43)

In [43]:
d = arange(1, 10)
sum(d), prod(d)

(45, 362880)

In [44]:
cumsum(d)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [45]:
cumprod(d)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)

In [46]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [47]:
np.diagonal(A)

array([ 0, 11, 22, 33, 44])

In [48]:
assert np.diagonal(A).sum() == np.trace(A) # trace = sum of diagonal

In [49]:
m = random.rand(3, 3)
m

array([[0.50158801, 0.01208161, 0.64968609],
       [0.99787652, 0.17790949, 0.41895437],
       [0.6720218 , 0.00547267, 0.52887436]])

In [50]:
# use axis parameter to specify how function behaves
m.max(), m.max(axis=0)

(0.9978765226915559, array([0.99787652, 0.17790949, 0.64968609]))

In [51]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [52]:
# reshape without copying underlying data
n, m = A.shape
B = A.reshape((1,n*m))

B

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30,
        31, 32, 33, 34, 40, 41, 42, 43, 44]])

Implement `image2vector()` that takes an input of shape (length, height, 3) and returns a vector of shape (length\*height\*3, 1).

In [53]:
def image2vector(image):
    """
    Argument:
    image -- a numpy array of shape (length, height, depth)
    
    Returns:
    v -- a vector of shape (length*height*depth, 1)
    """
    
    v = image.reshape(image.shape[0]*image.shape[1]*image.shape[2],1)
    
    return v

image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])

print ("image2vector(image) = " + str(image2vector(image)))

image2vector(image) = [[0.67826139]
 [0.29380381]
 [0.90714982]
 [0.52835647]
 [0.4215251 ]
 [0.45017551]
 [0.92814219]
 [0.96677647]
 [0.85304703]
 [0.52351845]
 [0.19981397]
 [0.27417313]
 [0.60659855]
 [0.00533165]
 [0.10820313]
 [0.49978937]
 [0.34144279]
 [0.94630077]]


In [54]:
# modify the array
B[0,0:5] = 5
B

array([[ 5,  5,  5,  5,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30,
        31, 32, 33, 34, 40, 41, 42, 43, 44]])

In [55]:
# also changed
A

array([[ 5,  5,  5,  5,  5],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [56]:
# creates a copy
B = A.flatten()
B

array([ 5,  5,  5,  5,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
       32, 33, 34, 40, 41, 42, 43, 44])

In [57]:
# can insert a dimension in an array
v = array([1,2,3])
v[:, newaxis], v[:,newaxis].shape, v[newaxis,:].shape

(array([[1],
        [2],
        [3]]),
 (3, 1),
 (1, 3))

In [58]:
repeat(v, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [59]:
tile(v, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [60]:
w = array([5, 6])

In [61]:
concatenate((v, w), axis=0)

array([1, 2, 3, 5, 6])

In [62]:
# deep copy
B = copy(A)
print('A',id(A)) # id() gets the object's address in the default CPython implementation
print('B',id(B))
C = A
print('C',id(C))

A 2059223597296
B 2059223797360
C 2059223597296
